# Generated by Django 5.0.6 on 2024-05-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='alumno',
            name='cui',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
